#!/bin/bash
#$ -N prep_dataset_197k
#$ -cwd
#$ -q short-sl7
#$ -o ./out/$JOB_NAME-$JOB_ID.out
#$ -e ./err/$JOB_NAME-$JOB_ID.err
#$ -l virtual_free=20G,disk=300G

module use /software/as/el7.2/EasyBuild/CRG/modules/all
module load Singularity/3.7.0
module load Python

CONTAINER='/users/cn/lsantus/containers/singularity/tfcpu.sif'
SCRIPT='/users/cn/lsantus/projects/FED/src/01_enformer/02_pred_eval.py'


singularity exec ${CONTAINER} python3 ${SCRIPT}
